### ISSUE TITLE
Unable to file bug after unlinking with bucket (and creating a new one)

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/FuzzManager#149]
I misfiled a bug, unlinked the bucket and tried to refile, but there is no longer a "file bug with best testcase option".

Screenshot:
<img width="1267" alt="screen shot 2015-11-21 at 10 15 47 am" src="https://cloud.githubusercontent.com/assets/488630/11319818/e24872a8-9038-11e5-897b-7c3f148bc732.png">

I was referring to bucket 1236, and had reported bug 1226892 before resolving that one as invalid.

**Comment by nth10sd** [comment]
I had matched with the old bucket because FuzzManager said there were matching buckets.

**Comment by choller** [comment]
I responded to you on IRC. I don't think there is a bug here because the bucket is empty. You can only file bugs if you have at least one crash in your bucket :)

**Comment by nth10sd** [comment]
I see, thanks!
