### ISSUE TITLE
[CrashManager] Add delete button to query interface

### ISSUE THREAD

**Issue by choller** [MozillaSecurity/FuzzManager#153]

**Comment by choller** [comment]
The delete button should POST the ids of the previous search result such that they can be mass-deleted (with confirmation).

**Comment by jschwartzentruber** [comment]
This will be more urgent with the containerization of the server. Alternative to POSTing a list of IDs, we could use the timestamp when the query was loaded as an implicit filter to the delete query. The confirmation view should include a breakdown of affected tools.
