### ISSUE TITLE
[CrashManager] Path stripping does not work properly for Windows crash stacks via cdb

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/FuzzManager#187]
The path stripping for the filename does not work properly for:
Assertion failure: block->graph().osrBlock(), at c:/Users/fuzz1win/trees/mozilla-central/js/src/jit/Lowering.cpp:4691
via
https://fuzzmanager.fuzzing.mozilla.org/crashmanager/crashes/223414/

This causes it to miss the matching bucket:
https://fuzzmanager.fuzzing.mozilla.org/crashmanager/signatures/1746/

**Comment by choller** [comment]
We need to do more here than just strip the windows paths properly.

Right now, the path sanitizing algorithm sanitizes paths to `/.+/File.cpp:[0-9]+` which breaks with windows paths because they don't start with `/`. The modified algorithm should probably return something like `.+[/\\]File.cpp:[0-9]+`

**Comment by choller** [comment]
Unfortunately the approach with backward slashes mentioned in the last comment does not work and we also need to keep the prefix of the path.

I committed a fix that supports Windows paths with forward slashes only by creating buckets with patterns like this: `([a-zA-Z]:)?/.+/File.cpp:[0-9]+`

This would break if we had backward slashes in the paths. @nth10sd are the paths always going to contain forward slashes only? Also, please check that the bucket is created correctly now.

Another approach would be to actively modify the output on windows to match linux/mac paths, but that would involve changing the crash data and that has other problems.

**Comment by nth10sd** [comment]
Yes, I think the slashes on Windows are always the reverse of Linux & Mac.

I'd say this is fixed by rev 708fba26c36038b8b798c173a2d182ac2d54e033 - there's another issue with stackFrame matching, but I'll file separately.

**Comment by nth10sd** [comment]
(at least, *almost always)

**Comment by nth10sd** [comment]
I mis-spoke, the forward slashes "/" at the end of the assertion failure message is likely output by the js shell, not something we change. At least I think this is the case, till we scale things up and have more data.
