### ISSUE TITLE
[CrashManager] functionNames matching not accounting for line endings

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/FuzzManager#188]
So in:
https://fuzzmanager.fuzzing.mozilla.org/crashmanager/signatures/1746/optimize/
it should match:
https://fuzzmanager.fuzzing.mozilla.org/crashmanager/crashes/223414/

but instead, it's suggesting a complete removal of all functionNames in the stackFrame.

I'm guessing this might be something to do with line endings, we should match based on excluding the line ending since it's CRLF on Windows and LF on POSIX.

**Comment by choller** [comment]
This doesn't seem to be a bug. The optimization is correct. Your issue does not have any stack because it was probably submitted before I committed the fix for your stack parsing.

I edited the issue and saved it (that causes a reparsing to happen), and now it fits fine.
