### ISSUE TITLE
UnboundLocalError: local variable 'rwMsg' referenced before assignment

### ISSUE THREAD

**Issue by jruderman** [MozillaSecurity/FuzzManager#192]
When I ran:

    funfuzz/dom/automation/domInteresting.py --submit ~/builds/mozilla-central-asan-opt/ /Users/jruderman/wtmp1/q3568-splice-reduced.html

I got this error from CrashInfo.py in FuzzManager:

    Traceback (most recent call last):
      File "funfuzz/dom/automation/domInteresting.py", line 760, in <module>
        directMain()
      File "funfuzz/dom/automation/domInteresting.py", line 745, in directMain
        br = BrowserResult(bc, bc.options.argURL or "about:blank", logPrefix, extraPrefs=extraPrefs, leaveProfile=True)
      File "funfuzz/dom/automation/domInteresting.py", line 662, in __init__
        createCollector.printCrashInfo(crashInfo)
      File "/Users/jruderman/funfuzz/util/createCollector.py", line 27, in printCrashInfo
        if crashInfo.createShortSignature() != "No crash detected":
      File "/Users/jruderman/FuzzManager/FTB/Signatures/CrashInfo.py", line 581, in createShortSignature
        if rwMsg:
    UnboundLocalError: local variable 'rwMsg' referenced before assignment

The output from ASan that triggered this:

    ASAN:DEADLYSIGNAL
    =================================================================
    ==92612==ERROR: AddressSanitizer: stack-overflow on address 0x7fff5f3fff98 (pc 0x0001000968d7 bp 0x7fff5f4007f0 sp 0x7fff5f3fffa0 T0)
    ==92612==WARNING: invalid path to external symbolizer!
    ==92612==WARNING: Failed to use and restart external symbolizer!
        #0 0x1000968d6 in __asan_memset (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x3f8d6)
    ...
        #255 0x10b6ef258 in PresShell::FlushPendingNotifications(mozilla::ChangesToFlush) (/Users/jruderman/builds/mozilla-central-asan-opt/dist/Nightly.app/Contents/MacOS/XUL+0x780b258)
    SUMMARY: AddressSanitizer: stack-overflow (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib+0x3f8d6) in __asan_memset
    ==92612==ABORTING

Submitting the same testcase with a non-ASan build succeeded: https://fuzzmanager.fuzzing.mozilla.org/crashmanager/crashes/255384/

**Comment by choller** [comment]
Try now :)

**Comment by jruderman** [comment]
Works now :)

https://fuzzmanager.fuzzing.mozilla.org/crashmanager/crashes/260427/
