### ISSUE TITLE
[CrashManager] IndexError: list index out of range issue with a specific regex in crashmanager

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/FuzzManager#199]
https://fuzzmanager.fuzzing.mozilla.org/crashmanager/signatures/1998/optimize/

shows an IndexError: list index out of range issue.

I had changed:

      "value": "/Assertion failure: zone\\->runtimeFromAnyThread\\(\\)\\->isHeapBusy\\(\\), at ([a-zA-Z]:)?(/|\\\\).+/jsgcinlines\\.h:[0-9]+/"

to:

      "value": "/Assertion failure: zone\\->runtimeFromAnyThread\\(\\).+, at ([a-zA-Z]:)?(/|\\\\).+/jsgcinlines\\.h:[0-9]+/"

Is this value a valid entry?

**Comment by choller** [comment]
Where is the stack trace for this issue?
