### ISSUE TITLE
List matching crashes in signature preview

### ISSUE THREAD

**Issue by jruderman** [MozillaSecurity/FuzzManager#202]
Signature preview currently shows the number of matching crashes. I'd like it to list the matching crashes as well, so I can be more sure that my signature is correct (or more easily understand why it's not).

**Comment by choller** [comment]
Pushed into production.

The edit view of the signatures now has two lists at the end, one for the new issues being added to the bucket and one for the issues that will be removed. There are two links next to the numbers on the top that you can use to jump to the respective list.
