### ISSUE TITLE
[EC2SpotManager] Unable to clear some fields when editing configurations.

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/FuzzManager#236]
After saving something into the "EC2 Userdata File" entry, it cannot seem to be cleared. I would delete the contents and save it, but when I reopen the configuration, the old contents is still present.

I had to resort to entering whitespace to "clear" the field, so it would be nice to be able to clear this.

**Comment by jschwartzentruber** [comment]
This also applies to fields: "EC2 Security Groups", "EC2 Userdata Macros", & "EC2 Allowed Regions"
and possibly others.

**Comment by choller** [comment]
The problem is likely that the fields are not reset to "None" when they are blanked out, but instead stored as empty strings which then override the parent. For the file field, the file in addition needs to be deleted.

**Comment by choller** [comment]
@jschwartzentruber I just pushed fixes for the list/dict fields as well as the ec2_userdata problem. Can you confirm that this is working now?

**Comment by jschwartzentruber** [comment]
This is working.
