### ISSUE TITLE
[EC2SpotManager] Allow multiple instance types

### ISSUE THREAD

**Issue by choller** [MozillaSecurity/FuzzManager#254]
We should allow multiple instance types in the EC2 configuration and select the cheapest combination of region and instance type.

**Comment by choller** [comment]
This is a P1 because it could potentially save some money when allocating EC2 instances.

There are several problems with this bug though:

1. We currently don't have any notion of "equivalency" for instances. For example, a c3.2xlarge is twice a c3.xlarge, so EC2SpotManager should either start one c3.2xlarge or two c3.xlarge. In order to solve this, we would probably need a mapping "instance type -> value" to establish relationships between the different sizes of instances that EC2 offers. Furthermore, we would have to define what the baseline is for this measurement and make the pool size use this measurement instead of being a fixed instance count. A good choice might be the number of CPU cores here.

2. While in production, we would have to make sure that only instance types are selected that our images are compatible with. So the user needs to be able to provide a list of eligible instances.

3. The fuzzing tool/script running on the instance needs to take into account that the machine can have any amount of CPU cores and auto-scale based on that.


For implementation, only 1. is really relevant, while 2+3 affects existing setups.

**Comment by jschwartzentruber** [comment]
I'm testing a partial fix for this issue. At this point we have c3.2xlarge, c4.2xlarge, and c5.2xlarge, m4.2xlarge, and m5.2xlarge which are mostly equivalent for our purposes, and being able to select from equivalent instance types would already yield a cost savings.

I'd propose fixing 1. from your comment in a separate issue where we redefine pool size to be a desired cpu count, and then configurations can specify instance types which have an acceptable min core count and core/memory ratio.

**Comment by jschwartzentruber** [comment]
Btw we should mention that allowing CPU core weighting of instance types is very close to [EC2 Spot Fleet](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html). I think that is still per-region, which makes it hard to compare.
