### ISSUE TITLE
python manage.py cleanup_old_crashes error with received a naive datetime

### ISSUE THREAD

**Issue by kkuehl** [MozillaSecurity/FuzzManager#366]
python manage.py cleanup_old_crashes with received a naive datetime
RESULT CODE: 0

ERROR OUTPUT:
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1393: RuntimeWarning: DateTimeField Bug.closed received a naive datetime (2017-10-08 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1393: RuntimeWarning: DateTimeField CrashEntry.created received a naive datetime (2017-09-27 00:00:00) while time zone support is active.
  RuntimeWarning)

STANDARD OUTPUT:

**Comment by jschwartzentruber** [comment]
Fixed by 4c9a2792b40be863818c1a27fecc35c759f15bba
