### ISSUE TITLE
django settings ALLOWED_HOSTS = []

### ISSUE THREAD

**Issue by kkuehl** [MozillaSecurity/FuzzManager#376]
/FuzzManager/server/server/settings.py
should have 
ALLOWED_HOSTS = ['*']
instead of 
ALLOWED_HOSTS = [ ]

or you get the following error:
w[Wed Oct 18 20:05:00.978014 2017] [wsgi:error] [pid 12:tid 140541544236800] Invalid HTTP_HOST header: '10.0.0.1:8000'. You may need to add u'10.0.0.1' to ALLOWED_HOSTS.

Or at least add documentation to tell the user to change this according to:
https://docs.djangoproject.com/en/1.11/ref/settings/#allowed-hosts

**Comment by kkuehl** [comment]
diff --git a/server/server/settings.py b/server/server/settings.py
index f60c34d..f906a75 100644
--- a/server/server/settings.py
+++ b/server/server/settings.py
@@ -36,7 +36,9 @@ except:
 # SECURITY WARNING: don't run with debug turned on in production!
 DEBUG = True
 
-ALLOWED_HOSTS = []
+ALLOWED_HOSTS = ['*']
+
+DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400
 
 
 # Application definition

**Comment by jschwartzentruber** [comment]
Per [my comment in #379](/MozillaSecurity/FuzzManager/pull/379#issuecomment-337923564), let's make this a documentation change instead of a permissive default.
