### ISSUE TITLE
DATA_UPLOAD_MAX_MEMORY_SIZE default too small

### ISSUE THREAD

**Issue by kkuehl** [MozillaSecurity/FuzzManager#377]
[Wed Oct 18 20:03:24.388579 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195] mod_wsgi (pid=12): Exception occurred processing WSGI script '/web/server/server/wsgi.py'.
[Wed Oct 18 20:03:24.388617 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195] Traceback (most recent call last):
[Wed Oct 18 20:03:24.388633 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 157, in __call__
[Wed Oct 18 20:03:24.388675 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]     response = self.get_response(request)
[Wed Oct 18 20:03:24.388684 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 124, in get_response
[Wed Oct 18 20:03:24.388699 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]     response = self._middleware_chain(request)
[Wed Oct 18 20:03:24.388708 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 43, in inner
[Wed Oct 18 20:03:24.388722 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]     response = response_for_exception(request, exc)
[Wed Oct 18 20:03:24.388731 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 83, in response_for_exception
[Wed Oct 18 20:03:24.388744 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]     response = debug.technical_500_response(request, *sys.exc_info(), status_code=400)
[Wed Oct 18 20:03:24.388753 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]   File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 84, in technical_500_response
[Wed Oct 18 20:03:24.388769 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]     html = reporter.get_traceback_html()
[Wed Oct 18 20:03:24.388776 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]   File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 327, in get_traceback_html
[Wed Oct 18 20:03:24.388788 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]     c = Context(self.get_traceback_data(), use_l10n=False)
[Wed Oct 18 20:03:24.388796 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]   File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 300, in get_traceback_data
[Wed Oct 18 20:03:24.388807 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]     'filtered_POST_items': list(self.filter.get_post_parameters(self.request).items()),
[Wed Oct 18 20:03:24.388813 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]   File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 167, in get_post_parameters
[Wed Oct 18 20:03:24.388826 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]     return request.POST
[Wed Oct 18 20:03:24.388831 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 126, in _get_post
[Wed Oct 18 20:03:24.388842 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]     self._load_post_and_files()
[Wed Oct 18 20:03:24.388847 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]   File "/usr/local/lib/python2.7/dist-packages/django/http/request.py", line 311, in _load_post_and_files
[Wed Oct 18 20:03:24.388860 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]     self._post, self._files = QueryDict(self.body, encoding=self._encoding), MultiValueDict()
[Wed Oct 18 20:03:24.388865 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]   File "/usr/local/lib/python2.7/dist-packages/django/http/request.py", line 269, in body
[Wed Oct 18 20:03:24.388877 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195]     raise RequestDataTooBig('Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.')
[Wed Oct 18 20:03:24.388895 2017] [wsgi:error] [pid 12:tid 140541535844096] [remote 172.19.0.1:5195] RequestDataTooBig: Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.

**Comment by jschwartzentruber** [comment]
Per [my comment in #379](/MozillaSecurity/FuzzManager/pull/379#issuecomment-337923564), let's make this a documentation change instead of a permissive default.
