### ISSUE TITLE
Internal Server Error: /crashmanager/rest/crashes/

### ISSUE THREAD

**Issue by kkuehl** [MozillaSecurity/FuzzManager#378]
docker-fuzzmanager | [Wed Oct 18 20:30:16.166825 2017] [wsgi:error] [pid 12:tid 140653773743872] Traceback (most recent call last):
docker-fuzzmanager | [Wed Oct 18 20:30:16.166828 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
docker-fuzzmanager | [Wed Oct 18 20:30:16.166829 2017] [wsgi:error] [pid 12:tid 140653773743872]     response = get_response(request)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166830 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
docker-fuzzmanager | [Wed Oct 18 20:30:16.166831 2017] [wsgi:error] [pid 12:tid 140653773743872]     response = self._get_response(request)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166833 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
docker-fuzzmanager | [Wed Oct 18 20:30:16.166834 2017] [wsgi:error] [pid 12:tid 140653773743872]     response = self.process_exception_by_middleware(e, request)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166835 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
docker-fuzzmanager | [Wed Oct 18 20:30:16.166836 2017] [wsgi:error] [pid 12:tid 140653773743872]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166838 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
docker-fuzzmanager | [Wed Oct 18 20:30:16.166839 2017] [wsgi:error] [pid 12:tid 140653773743872]     return view_func(*args, **kwargs)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166840 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 90, in view
docker-fuzzmanager | [Wed Oct 18 20:30:16.166842 2017] [wsgi:error] [pid 12:tid 140653773743872]     return self.dispatch(request, *args, **kwargs)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166843 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 489, in dispatch
docker-fuzzmanager | [Wed Oct 18 20:30:16.166845 2017] [wsgi:error] [pid 12:tid 140653773743872]     response = self.handle_exception(exc)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166846 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in handle_exception
docker-fuzzmanager | [Wed Oct 18 20:30:16.166850 2017] [wsgi:error] [pid 12:tid 140653773743872]     self.raise_uncaught_exception(exc)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166851 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 486, in dispatch
docker-fuzzmanager | [Wed Oct 18 20:30:16.166852 2017] [wsgi:error] [pid 12:tid 140653773743872]     response = handler(request, *args, **kwargs)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166855 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 21, in create
docker-fuzzmanager | [Wed Oct 18 20:30:16.166864 2017] [wsgi:error] [pid 12:tid 140653773743872]     self.perform_create(serializer)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166867 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 26, in perform_create
docker-fuzzmanager | [Wed Oct 18 20:30:16.166868 2017] [wsgi:error] [pid 12:tid 140653773743872]     serializer.save()
docker-fuzzmanager | [Wed Oct 18 20:30:16.166869 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 215, in save
docker-fuzzmanager | [Wed Oct 18 20:30:16.166871 2017] [wsgi:error] [pid 12:tid 140653773743872]     self.instance = self.create(validated_data)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166872 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/web/server/crashmanager/serializers.py", line 53, in create
docker-fuzzmanager | [Wed Oct 18 20:30:16.166883 2017] [wsgi:error] [pid 12:tid 140653773743872]     attrs['product'] = Product.objects.get_or_create(**attrs['product'])[0]
docker-fuzzmanager | [Wed Oct 18 20:30:16.166885 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
docker-fuzzmanager | [Wed Oct 18 20:30:16.166887 2017] [wsgi:error] [pid 12:tid 140653773743872]     return getattr(self.get_queryset(), name)(*args, **kwargs)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166888 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 464, in get_or_create
docker-fuzzmanager | [Wed Oct 18 20:30:16.166890 2017] [wsgi:error] [pid 12:tid 140653773743872]     return self.get(**lookup), False
docker-fuzzmanager | [Wed Oct 18 20:30:16.166891 2017] [wsgi:error] [pid 12:tid 140653773743872]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 384, in get
docker-fuzzmanager | [Wed Oct 18 20:30:16.166892 2017] [wsgi:error] [pid 12:tid 140653773743872]     (self.model._meta.object_name, num)
docker-fuzzmanager | [Wed Oct 18 20:30:16.166893 2017] [wsgi:error] [pid 12:tid 140653773743872] MultipleObjectsReturned: get() returned more than one Product -- it returned 8!

**Comment by kkuehl** [comment]
I deleted my database and this went away, not sure what the correct fix was/is.

**Comment by jschwartzentruber** [comment]
Yeah, this looks weird... is it possible you were creating objects from the Django shell? We should add unique constraints so the error happens when duplicates are created.

**Comment by kkuehl** [comment]
I wasn't creating any objects via the Django shell. I have had the database for a long time and was just using python ./manage migrate.
Everything seems fine now that I started over, not sure what the correct way to upgrade was though.

**Comment by jschwartzentruber** [comment]
`python manage.py migrate` should be enough. If you see it again then file another issue I guess.
