### ISSUE TITLE
[CovManager] File does not exist: /web/server/crashmanager/static/js/vuejs-datepicker.js

### ISSUE THREAD

**Issue by kkuehl** [MozillaSecurity/FuzzManager#381]
[Fri Oct 20 18:13:50.004852 2017] [core:info] [pid 14:tid 139716980578048] [client 172.20.0.1:42598] AH00128: File does not exist: /web/server/crashmanager/static/js/vuejs-datepicker.js, referer: http://localhost:8000/crashmanager/signatures/new/?crashid=2011

**Comment by jschwartzentruber** [comment]
Looks like this is WIP accidentally added in 2adb85c7fa0628f291ed6f80781ac71793b38ba8?
