### ISSUE TITLE
 RuntimeError("Fatal error parsing ASan trace (Index mismatch, got index X but expected Y error with proposed fix

### ISSUE THREAD

**Issue by kkuehl** [MozillaSecurity/FuzzManager#392]
When terminating a Firefox Asan browser build with signal SIGTERM.

After adding some debugging information to print out parts and the index vs expectedIndex:

2017-11-08 14:45:22,836 - root - INFO - Terminated by signal 15
parts = [u'#0', u'0x7f506559c0d6', u'in', u'mozilla::ipc::MessageChannel::OnChannelErrorFromLink()', u'/builds/worker/workspace/build/src/ipc/glue/MessageChannel.cpp:2543:13']
index = 0 expectedIndex 0
parts = [u'#1', u'0x7f50655a0db7', u'in', u'OnChannelError', u'/builds/worker/workspace/build/src/ipc/glue/MessageLink.cpp:397:12']
index = 1 expectedIndex 1
parts = [u'#2', u'0x7f50655a0db7', u'in', u'non-virtual', u'thunk', u'to', u'mozilla::ipc::ProcessLink::OnChannelError()', u'/builds/worker/workspace/build/src/ipc/glue/MessageLink.cpp:389']
index = 2 expectedIndex 2
parts = [u'#3', u'0x7f506554f791', u'in', u'event_persist_closure', u'/builds/worker/workspace/build/src/ipc/chromium/src/third_party/libevent/event.c:1580:9']
index = 3 expectedIndex 3
parts = [u'#4', u'0x7f506554f791', u'in', u'event_process_active_single_queue', u'/builds/worker/workspace/build/src/ipc/chromium/src/third_party/libevent/event.c:1639']
index = 4 expectedIndex 4
parts = [u'#5', u'0x7f5065546ef9', u'in', u'event_process_active', u'/builds/worker/workspace/build/src/ipc/chromium/src/third_party/libevent/event.c:1741:9']
index = 5 expectedIndex 5
parts = [u'#6', u'0x7f5065546ef9', u'in', u'event_base_loop', u'/builds/worker/workspace/build/src/ipc/chromium/src/third_party/libevent/event.c:1961']
index = 6 expectedIndex 6
parts = [u'#7', u'0x7f506550825d', u'in', u'base::MessagePumpLibevent::Run(base::MessagePump::Delegate*)', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/message_pump_libevent.cc:373:7']
index = 7 expectedIndex 7
parts = [u'#8', u'0x7f50655031db', u'in', u'RunInternal', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/message_loop.cc:326:10']
index = 8 expectedIndex 8
parts = [u'#9', u'0x7f50655031db', u'in', u'RunHandler', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/message_loop.cc:319']
index = 9 expectedIndex 9
parts = [u'#10', u'0x7f50655031db', u'in', u'MessageLoop::Run()', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/message_loop.cc:299']
index = 10 expectedIndex 10
parts = [u'#11', u'0x7f5065520679', u'in', u'base::Thread::ThreadMain()', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/thread.cc:181:16']
index = 11 expectedIndex 11
parts = [u'#12', u'0x7f5065511f4c', u'in', u'ThreadFunc(void*)', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/platform_thread_posix.cc:38:13']
index = 12 expectedIndex 12
parts = [u'#13', u'0x7f50841497fb', u'in', u'start_thread', u'(/lib/x86_64-linux-gnu/libpthread.so.0+0x77fb)']
index = 13 expectedIndex 13
parts = [u'#0', u'0x7f3e4e0680d6', u'in', u'mozilla::ipc::MessageChannel::OnChannelErrorFromLink()', u'/builds/worker/workspace/build/src/ipc/glue/MessageChannel.cpp:2543:13']
index = 0 expectedIndex 0
parts = [u'#1', u'0x7f3e4e06cdb7', u'in', u'OnChannelError', u'/builds/worker/workspace/build/src/ipc/glue/MessageLink.cpp:397:12']
index = 1 expectedIndex 1
parts = [u'#2', u'0x7f3e4e06cdb7', u'in', u'non-virtual', u'thunk', u'to', u'mozilla::ipc::ProcessLink::OnChannelError()', u'/builds/worker/workspace/build/src/ipc/glue/MessageLink.cpp:389']
index = 2 expectedIndex 2
parts = [u'#3', u'0x7f3e4e01b791', u'in', u'event_persist_closure', u'/builds/worker/workspace/build/src/ipc/chromium/src/third_party/libevent/event.c:1580:9']
index = 3 expectedIndex 3
parts = [u'#4', u'0x7f3e4e01b791', u'in', u'event_process_active_single_queue', u'/builds/worker/workspace/build/src/ipc/chromium/src/third_party/libevent/event.c:1639']
index = 4 expectedIndex 4
parts = [u'#5', u'0x7f3e4e012ef9', u'in', u'event_process_active', u'/builds/worker/workspace/build/src/ipc/chromium/src/third_party/libevent/event.c:1741:9']
index = 5 expectedIndex 5
parts = [u'#6', u'0x7f3e4e012ef9', u'in', u'event_base_loop', u'/builds/worker/workspace/build/src/ipc/chromium/src/third_party/libevent/event.c:1961']
index = 6 expectedIndex 6
parts = [u'#7', u'0x7f3e4dfd425d', u'in', u'base::MessagePumpLibevent::Run(base::MessagePump::Delegate*)', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/message_pump_libevent.cc:373:7']
index = 7 expectedIndex 7
parts = [u'#8', u'0x7f3e4dfcf1db', u'in', u'RunInternal', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/message_loop.cc:326:10']
index = 8 expectedIndex 8
parts = [u'#9', u'0x7f3e4dfcf1db', u'in', u'RunHandler', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/message_loop.cc:319']
index = 9 expectedIndex 9
parts = [u'#10', u'0x7f3e4dfcf1db', u'in', u'MessageLoop::Run()', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/message_loop.cc:299']
index = 10 expectedIndex 10
parts = [u'#11', u'0x7f3e4dfec679', u'in', u'base::Thread::ThreadMain()', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/thread.cc:181:16']
index = 11 expectedIndex 11
parts = [u'#12', u'0x7f3e4dfddf4c', u'in', u'ThreadFunc(void*)', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/platform_thread_posix.cc:38:13']
index = 12 expectedIndex 12
parts = [u'#13', u'0x7f3e6cc157fb', u'in', u'start_thread', u'(/lib/x86_64-linux-gnu/libpthread.so.0+0x77fb)']
index = 13 expectedIndex 13
parts = [u'#14', u'0x7f5083177b0e', u'in', u'clone', u'/build/glibc-CxtIbX/glibc-2.26/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95']
index = 14 expectedIndex 14
parts = [u'#0', u'0x4a4796', u'in', u'__interceptor_pthread_create', u'/builds/slave/moz-toolchain/src/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:245:3']
index = 0 expectedIndex 0
parts = [u'#1', u'0x7f506551122c', u'in', u'CreateThread', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/platform_thread_posix.cc:135:14']
index = 1 expectedIndex 1
parts = [u'#2', u'0x7f506551122c', u'in', u'PlatformThread::Create(unsigned', u'long,', u'PlatformThread::Delegate*,', u'unsigned', u'long*)', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/platform_thread_posix.cc:146']
index = 2 expectedIndex 2
parts = [u'#3', u'0x7f50655200be', u'in', u'base::Thread::StartWithOptions(base::Thread::Options', u'const&)', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/thread.cc:99:8']
index = 3 expectedIndex 3
parts = [u'#4', u'0x7f50655a2c87', u'in', u'mozilla::ipc::ProcessChild::ProcessChild(int)', u'/builds/worker/workspace/build/src/ipc/glue/ProcessChild.cpp:24:5']
index = 4 expectedIndex 4
parts = [u'#5', u'0x7f506f22266d', u'in', u'ContentProcess', u'/builds/worker/workspace/build/src/obj-firefox/dist/include/mozilla/dom/ContentProcess.h:31:7']
index = 5 expectedIndex 5
parts = [u'#6', u'0x7f506f22266d', u'in', u'XRE_InitChildProcess(int,', u'char**,', u'XREChildData', u'const*)', u'/builds/worker/workspace/build/src/toolkit/xre/nsEmbedFunctions.cpp:650']
index = 6 expectedIndex 6
parts = [u'#7', u'0x4ec1e3', u'in', u'content_process_main', u'/builds/worker/workspace/build/src/browser/app/../../ipc/contentproc/plugin-container.cpp:63:30']
index = 7 expectedIndex 7
parts = [u'#8', u'0x4ec1e3', u'in', u'main', u'/builds/worker/workspace/build/src/browser/app/nsBrowserApp.cpp:285']
index = 8 expectedIndex 8
parts = [u'#9', u'0x7f50830841c0', u'in', u'__libc_start_main', u'/build/glibc-CxtIbX/glibc-2.26/csu/../csu/libc-start.c:308']
**index = 9 expectedIndex 9
parts = [u'#14', u'0x7f3e6bc43b0e', u'in', u'clone', u'/build/glibc-CxtIbX/glibc-2.26/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95']
index = 14 expectedIndex 10
Error parsing ASan trace (Index mismatch, got index 14 but expected 10)
parts = [u'#0', u'0x4a4796', u'in', u'__interceptor_pthread_create', u'/builds/slave/moz-toolchain/src/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:245:3']
index = 0 expectedIndex 0**
parts = [u'#1', u'0x7f3e4dfdd22c', u'in', u'CreateThread', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/platform_thread_posix.cc:135:14']
index = 1 expectedIndex 1
parts = [u'#2', u'0x7f3e4dfdd22c', u'in', u'PlatformThread::Create(unsigned', u'long,', u'PlatformThread::Delegate*,', u'unsigned', u'long*)', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/platform_thread_posix.cc:146']
index = 2 expectedIndex 2
parts = [u'#3', u'0x7f3e4dfec0be', u'in', u'base::Thread::StartWithOptions(base::Thread::Options', u'const&)', u'/builds/worker/workspace/build/src/ipc/chromium/src/base/thread.cc:99:8']
index = 3 expectedIndex 3
parts = [u'#4', u'0x7f3e4e06ec87', u'in', u'mozilla::ipc::ProcessChild::ProcessChild(int)', u'/builds/worker/workspace/build/src/ipc/glue/ProcessChild.cpp:24:5']
index = 4 expectedIndex 4
parts = [u'#5', u'0x7f3e57cee66d', u'in', u'ContentProcess', u'/builds/worker/workspace/build/src/obj-firefox/dist/include/mozilla/dom/ContentProcess.h:31:7']
index = 5 expectedIndex 5
parts = [u'#6', u'0x7f3e57cee66d', u'in', u'XRE_InitChildProcess(int,', u'char**,', u'XREChildData', u'const*)', u'/builds/worker/workspace/build/src/toolkit/xre/nsEmbedFunctions.cpp:650']
index = 6 expectedIndex 6
parts = [u'#7', u'0x4ec1e3', u'in', u'content_process_main', u'/builds/worker/workspace/build/src/browser/app/../../ipc/contentproc/plugin-container.cpp:63:30']
index = 7 expectedIndex 7
parts = [u'#8', u'0x4ec1e3', u'in', u'main', u'/builds/worker/workspace/build/src/browser/app/nsBrowserApp.cpp:285']
index = 8 expectedIndex 8
parts = [u'#9', u'0x7f3e6bb501c0', u'in', u'__libc_start_main', u'/build/glibc-CxtIbX/glibc-2.26/csu/../csu/libc-start.c:308']
index = 9 expectedIndex 9

Instead of raising the error, I did the following to at least let things keep functioning in FTB/Signatures/CrashInfo.py

            if not expectedIndex == index:
                print("Error parsing ASan trace (Index mismatch, got index %s but expected %s)" % (index, expectedIndex))
                # set index to expectedIndex
                index = expectedIndex
               # raise RuntimeError("Fatal error parsing ASan trace (Index mismatch, got index %s but expected %s)" % (index, expectedIndex))

Let me know of what this is a bad idea. I don't see why the index gets out of sync in the above example, but it happens every time.

**Comment by jschwartzentruber** [comment]
Looks like this is due to e10s and ASan reports clobbering each other. Frame 14 is probably from the first stack and gets printed much later for some reason. If this came from DOMFuzz, it's not ready for e10s yet. Otherwise you should take a look at [FFPuppet](//github.com/MozillaSecurity/ffpuppet) which solves this by writing to multiple files instead of stderr.

**Comment by jschwartzentruber** [comment]
This is caused by simultaneous reports getting intermixed. Fixed is to use [FFPuppet](https://github.com/MozillaSecurity/ffpuppet) or set `ASAN_OPTIONS=log_path=/path/to/logs` to get each process report separately.
