### ISSUE TITLE
[CrashManager] View Signatures features requests

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/FuzzManager#633]
- Add the ability to sort buckets by size. The addition of this feature on the signatures page will help prioritize issues during triage.
- Highlight signatures with bugs that cannot be accessed.
- Buckets that have not seen reports for (x) duration. This will help identify bug that could possibly be closed.

**Comment by jschwartzentruber** [comment]
> * Add the ability to sort buckets by size. The addition of this feature on the signatures page will help prioritize issues during triage.

This was fixed by migrating this view to Vue.
  
> * Highlight signatures with bugs that cannot be accessed.

Fixed by adding inaccessible bug notifications.

> * Buckets that have not seen reports for (x) duration. This will help identify bug that could possibly be closed.

This can be visualized now with the addition of graphs.
