### ISSUE TITLE
Add Javascript build system for Vue.js

### ISSUE THREAD

**Issue by La0** [MozillaSecurity/FuzzManager#647]
In order to kickstart ne Vue.js developments on Crash Manager, we would first add webpack and the vue.js build chain.

A production build would be implemented through Taskcluster CI (on a recent node docker image)

The code would live in a new`frontend` directory at the root of the project, and would embed:
- npm configuration
- webpack configuration
- a dummy vue.js single file component

The dummy vue.js component would then be loaded into the signature edition page of crash manager, to showcase the build system.

**Comment by pyoor** [comment]
Closing this issue as it appears to have been completed.  Please reopen if I'm missing something.
