### ISSUE TITLE
Bug suggestion when creating a new Bugzilla bug

### ISSUE THREAD

**Issue by La0** [MozillaSecurity/FuzzManager#681]
The main goal is to provide a list of existing bugs matching a summary, when users are creating a bug through `crashes/<crashid>/createbug/`.

A new Vue.js component will be created that will use the user's Bugzilla Token from #676 and query the `possible_duplicates` endpoint.
If duplicates are found, a table listing them will be displayed below the summary, including these informations:
- Bug ID, with a link towards that bug
- Summary
- Component
- Status

An action button will be added on each line to assign the crash to that bug. This will require a new API endpoint to assign an existing Bugzilla Bug to a crash.

This endpoint would be available as `PUT rest/crashes/<crashid>/external-bug`, where the input serializer will expect:
- a bug provider ID
- an external bug ID
The endpoint will then simply create a new `Bug` instance for that provider and external bug id, and assigning the bug to the crash bucket (exactly like in `views.createExternalBug`)

If no existing bug is selected, the bug creation continues as before, using the `BugzillaProvider` class.

## References

- API doc for [possible_duplicates](https://bmo.readthedocs.io/en/latest/api/core/v1/bug.html?highlight=duplicates#possible-duplicates)
- Example [request](https://bugzilla-dev.allizom.org/rest/bug/possible_duplicates?product=Firefox&product=Core&product=Toolkit&summary=fenix+issue+with+sidebar&limit=12&include_fields=id%2Csummary%2Cstatus%2Cresolution%2Cupdate_token%2Ccc%2Ccomponent) - would need an authenticated account

## Current display on bugzilla

For reference, this is how it looks on Bugzilla when trying to fill a bug:

![Screenshot_2021-05-25 Enter A Bug](https://user-images.githubusercontent.com/101004/119495234-7e662480-bd62-11eb-8526-b53170ce61af.png)

**Comment by jschwartzentruber** [comment]
> An action button will be added on each line to assign the crash to that bug. This will require a new API endpoint to assign an existing Bugzilla Bug to a crash.
> 
> This endpoint would be available as PUT rest/crashes/<crashid>/external-bug, where the input serializer will expect:

I think in both these sentences, you mean bucket, not crash. Bugs are linked in the `Bucket` model.

So your UI would look very similar to the Bugzilla reference, but in place of the `Follow bug` button, would be a "Use this bug instead of creating a new one" button. 👍🏻 

In terms of the implementation, why not implement as a `PATCH` on the bucket endpoint (`PATCH /rest/buckets/<bucketid>/`)? You would need to add a field like `bug_provider`, but we already do this in the `CrashEntry` serializer to represent `TestCase` fields directly on the `CrashEntry` API.

**Comment by La0** [comment]
Agreed, I meant `Bucket`, there is no modification to the DB models here.

> So your UI would look very similar to the Bugzilla reference, but in place of the Follow bug button, would be a "Use this bug instead of creating a new one" button. 👍🏻

Exactly !
