### ISSUE TITLE
Vueify bugzilla product & component selection

### ISSUE THREAD

**Issue by La0** [MozillaSecurity/FuzzManager#682]
A new Vue.js component should be created to allow a user picking a Bugzilla product and component.

It will be used on several pages:
- Bugzilla Bug template creation and edition
- Bugzilla Bug publication

It will display 3 select fields:
1. the list of Bugzilla providers, displaying their hostname
2. the list of products for that provider hostname
3. the list of components for the selected product.

First we'll need a new read-only API viewset to list available providers on `/rest/providers`. The viewset should simply exports all 3 fields: `classname`, `hostname` and `url_template`.

The vue.js component would fetch the providers when mounted, and list all the `classname=BugzillaProvider` ones. When a provider is selected it will :
1. look in localStorage if the key `bugzilla-products-{hostname}` is available
2. if it's available use it to display products
3. otherwise, load `https://{hostname}/latest/configuration` and store the components and products in localstorage (not the full payload)

When a product is selected, display the components from that product.

Finally, an extra button is added to refresh the data loaded from the bugzilla instance into localstorage. It's named "Refresh" and displayed next to the provider list when a provider is selected.

This code will replace the javascript implementation in `crashmanager/templates/bugzilla/create_form.html`.

## Configuration parsing and storage

The configuration for BMO is available at https://bugzilla.mozilla.org/latest/configuration (:warning: it's a laaaarge JSON).

We are only interested by a few keys in that file, so we can store a subset of data in `localStorage`:

- keep `version`
- iterate over `product` to build the list `products`
  - filter on `is_active=true`
  - build a new dict with key `name`, `id` and an empty array `components`
  - iterate over each `component`:
    - filter on `is_active=true`
    - only keep the name in the array

You should end up with the following structure:

```json
{
  "version": "20210517.1",
  "products": [
    {
      "id" : 1,
      "name" : "Taskcluster",
      "components" : [
         "General",
         "Operations and Service requests",
         ...
      ]
    },
    ....
  ],
}
```

**Comment by jschwartzentruber** [comment]
Sounds good to me. Can the rest endpoint be `/rest/bugproviders` though? Who knows, we might have other "providers" in the future.

Originally I think we discussed having the localstorage cache valid for 1 week. Is this what you were thinking?

**Comment by jschwartzentruber** [comment]
> Just a note but https://bugzilla.mozilla.org/latest/configuration is a Mozilla specific endpoint. We should probably ensure that the names of the components associated with the provider are for a moz-specific bugzilla provider.

This was mentioned in the proposal above. The provider hostname is included in the localstorage key.

**Comment by pyoor** [comment]
I guess I meant more in regards to the naming convention we're using for the django models since this approach would be specific to the moz-specific bugzilla instance.  Though, the alternative would be to just fail silently if that endpoint doesn't exist (which I'm fine with as well).

**Comment by jschwartzentruber** [comment]
Yeah, BMO enables the BzAPI shim but others (I checked Apache & Redhat Bugzillas) do not. I guess it should just gracefully fail and not do any auto-completion if `{hostname}/latest/configuration` isn't available.

**Comment by La0** [comment]
To summarize your comments, this changes a few minor things:
- API call towards `https://{hostname}/latest/configuration` should allow failures and display 2 text inputs instead of selects.
- The API endpoint to list bug providers will use the url `/rest/bugproviders` (instead of `/rest/providers` mentionned above)
- A storage timestamp will be added in the `localStorage` payload to allow automatic cache-invalidation after a week:
   1. add key `stored` with current timestamp when the configuration is cached
   2. when checking if the cache is available, also validate that the diff between now and `stored` is less that a week
   3. if it's over a week, ignore the cache and make a new API call towards the bugzilla instance
