### ISSUE TITLE
Vueification of Bugzilla comment publication

### ISSUE THREAD

**Issue by La0** [MozillaSecurity/FuzzManager#694]
The main goals of this work are:
- remove HTML rendering related to comment publication from the Python `Provider` implementations
- use Vue.js component to publish Bugzilla comments instead of Python code

Python methods removed:
- `BugzillaProvider.handlePOSTComment`
- `BugzillaREST.createComment`

Bugzilla API calls needed in Javascript:
- [comment publication](https://bmo.readthedocs.io/en/latest/api/core/v1/comment.html?highlight=comment#create-comments)
- [attachment publication](https://bmo.readthedocs.io/en/latest/api/core/v1/attachment.html?highlight=attachment#create-attachment)

Data needed:
 - bugzilla bug id to comment on
    -  from associated bucket (provided as a prop)
    - or from user
 - text comment from user
 - is the comment private (from user)
 - text comment from potential template
 - ~~crash data from user~~ crash data is not present in the current form, but supported by provider
 - test case from user

The `views.createExternalBugComment` method will support `GET` requests only, rendering a new HTML template using a new Vue.js component

The component would allow a user to:
- select a provider
- select a bugzilla bug id (if not already provided)
- select a bugzilla comment template
- display text input for comment
- display rendered comment when using a template (in a dedicated HTML paragraph, read-only)
- input test case as text (in a textarea)
- input private field (as a checkbox)

On submit, the component would query the Bugzilla API to:
- create a comment, and display errors if any,
- create attachments for crash data and test case (when present), and display errors if any
- finally display a link toward the bugzilla comment

A new API endpoint (`POST` on `rest/crashes/<id>/comment`) would be created to store metadata relevant to the comment, its serializer would use as input:
- crash entry ID
- provider ID
- comment ID on the provider (so the bugzilla comment ID)
- rendered text comment
This endpoint would then call a new method on the Bug provider `hook_comment_created`, passing all received data from the frontend.
The Bugzilla implementation would do nothing.

Here is a mockup of the new page:
![mockup_comment_publish](https://user-images.githubusercontent.com/101004/120320611-ac0f1880-c2e2-11eb-890f-d783a60346c7.png)

**Comment by jschwartzentruber** [comment]
This means the frontend will be interpolating any placeholders in the template? ([`substituteTemplateForCrash`](https://github.com/MozillaSecurity/FuzzManager/blob/495e9cd2a01f289cb6fd487da216cc8485198468/server/crashmanager/Bugtracker/BugzillaProvider.py#L86)), or the backend would continue to do that?

"Your text comment" input is pre-populated from the template, but can be edited. Right?

How does the test case field behave when the test case is binary?

nits:
"Your text comment" -> "Comment"
"Rendered comment with template XXX" -> "Preview"

**Comment by La0** [comment]
After our discussion from today:
- test case is displayed and editable only when non-binary
- test case filename is editable
- we'll use [mustache](https://github.com/janl/mustache.js/) to render the comment from the template (no backend rendering)
- text comment is pre-populated from the template (and updated when switching of templates), but can be edited
