### ISSUE TITLE
Implement notifications for crashmanager

### ISSUE THREAD

**Issue by La0** [MozillaSecurity/FuzzManager#706]
## Notification targets

- Hits generated by crashmanager watches
- Notify on security bugs that can’t be accessed by FuzzManager
    - Notify all users with bucket crashes in their toolfilter
    - Likely need to test if a bug is made inaccessible after it was initially assigned to a bucket

## Use Django form for user settings

The current `usersettings` view is using several `POST` actions and could be simplified by using a single Django form:
- select tools for default filters
- select default provider
- select default template

Then we would extend that form to allow a user to configure:
- its email address (required to send email notifications)
- which notifications the user wants to receive
    - one checkbox (boolean field) per notification type (we only have `inaccessible_bug` & `bucket_hit`)

This work should be done in several Merge requests:
1. refactor the current view to use a Form
2. add email field
3. add notifications

## django-notifications & DB model

We would use the open-source Django app [django-notifications](https://pypi.org/project/django-notifications-hq/) to add a new Database model `Notification`.
This app is "sold" as a look-alike for Github notifications:
> django-notifications is for building something like Github “Notifications”

The new [model](https://github.com/django-notifications/django-notifications/blob/master/notifications/base/models.py#L140) allows us to store a notification for one or more users, with:
- a message decoupled in action, verb, time + optional target object
- if the message was already `emailed`

We would need to implement a method to get all potential recipients for a given notification, following these rules:
- all users watching a bucket (through `BucketWatch` model), when the bucket has a new hit
    - executed in `triage_new_crashes`
- all users with related bucket crashes in their toolfilter, when a bug is inaccessible by the backend Bugzilla user 
    - executed in `bug_update_status`

As `django-notifications` allows us to send notifications through a Django signal, the implementation would look like:

```python
# When receiving a new crash in a bucket
notify.send(
    recipient=bucket.watchers.all(),
    actor=bucket,
    verb="bucket_hit",
    target=crash_entry,
    level="INFO",
    description="the bucket XXX received a new crash entry YYY"
)
```

Each user would get a `Notification` instance with the relevant informations, allowing him to acknowledge his own notification.

## Mail notifications

The app `django-notifications` does **NOT** implement any mail functionality, but it has an `emailed` field on the `Notification` model.

We would implement a new Django management command named `notify` that would:
- iterate over all notifications with `emailed=False`
- check that the linked user has set its email
- check that the linked user is still watching this notification type
- build an email body using a Django template
- send the email through Django builtin system (using instance settings)
- update the `emailed` field on the notification to `True`

It would be the responsibility of the instance administrators to run that management command regularly as a cron (every X minutes).

## Interface changes

The goal is to create a user experience close to Github notification system:
- Notification icon adjacent to user icon
- Clicking icon takes you to a separate page listing unread notifications
- Clicking notification takes you to area of interest (i.e. the watched bucket)
- Add means for dismissing notifications

### Unread notifications

The `django-notifications` app provides an `unread()` queryset: we would use that in a new List API view exposed as `/rest/inbox` to list all unread notifications for the connected user. 
The serializer might be a bit hard to setup, as we need to support different related objects but it's [possible using different sub-serializers](https://github.com/django-notifications/django-notifications#serializing-the-django-notifications-model).

A new Vue.js component would also be implemented and served as a simple Details view on `/inbox` to display all notifications, alongside a **Dismiss** button (see below for details).

Each notification would be processed by the Vue.js component, displaying custom information for each `verb`, and using the related `actor` and `target` objects to build links toward pages for these objects:
- crash entry link
- bucket detail link

### Dismissing notifications

The `django-notifications` app provides an two means of deletion:
- soft delete by setting a `deleted` boolean to `True
- hard `delete()` that removes the `Notification` instance from database

We would implement one of these method on a new Delete API endpoint exposed as  `DELETE /rest/inbox/<ID>`, removing the notification from the Vue.js list describe above on successfull deletions.

### Notification icon

The `django-notifications` app provides a template tag `notifications_unread` to get the number of notifications users for the current user.

We would simply display an icon with the number of notification when there are any notifications. The display would be updated while browsing on the website.

The app also provides means to get live notification count through Javascript, but it seems overkill to implement that (as users should not get a LOT of notifications in short burst of time).

## Merge requests

The following merge requests would be produced in that order:
1. refactor user settings to use a Form
2. add email field to User model & user settings
3. add notifications boolean fields to User model & user settings
4. add django-notifications and publish both notifications types from management commands
5. Build the unread page
   - Vue.js component to list and display notifications
   - API to list notifications
   - Django page to expose the Vue.js component
   - notification icon
6. Add the dismiss action
   - Vue.js component for dismiss
   - API to delete notification
7. Push notification support
   - Vue.js component to display notification number and use the browser [Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API)
   - Support `?after=timestamp` API parameter

**Comment by EvaBardou** [comment]
Regarding the **Merge Requests** section, I think it would be better to group the following tasks in the same MR:
```
1. refactor user settings to use a Form
2. add email field to User model & user settings
3. add notifications boolean fields to User model & user settings
```

Step 2 and 3, will both only add a few lines in `User` model and `UserSettings` form.

It should be easier to maintain an unique MR (preventing chained rebases).
Also, the 3 steps deal with the same subject, which is: **User settings refactoring**.

**Comment by La0** [comment]
And here is a rough mockup of the display using a single form (new fields at the bottom):

![Screenshot 2021-06-14 at 17-02-41 https fuzzmanager teklia com](https://user-images.githubusercontent.com/101004/121914378-7fbbb900-cd32-11eb-955b-a85fa1dc699f.png)

**Comment by jschwartzentruber** [comment]
I like it. To be clear, there's no facility in this implementation for browser push notifications, only viewing via the icon/inbox, or push via email. Is that right?

Regarding email field in user settings: what about SSO? Changing the email would break login for SSO users. Maybe we also need a global setting (in settings.py) to say whether email should be editable.

For the notifications table in settings, please make each checkbox+label on a new line like tools.

**Comment by La0** [comment]
Regarding [push notifications](https://developer.mozilla.org/en-US/docs/Web/API/Push_API), we can implement them as a followup task (this does not change anything on the base implementation above)

A Vue.js component would be used on every page load to fetch the current number of notifications and any new notifications since the last fetch.
This could be done using the API needed to list unread notifications on the inbox page (using an optional `?after=timestamp` parameter)
The endpoint would be polled every X minutes: no need for a websocket implementation here, as it seems a tad overkill.

---- 

As discussed, I was not aware of the SSO usage. Your suggestion is good: we'll add an instance setting to disable email edition (and update the form configuration accordingly).

**Comment by La0** [comment]
Closing this one in favor of separate issues.
