### ISSUE TITLE
Dismiss notifications

### ISSUE THREAD

**Issue by La0** [MozillaSecurity/FuzzManager#713]
Refs #706 

The `django-notifications` app provides an two means of deletion:
- soft delete by setting a `deleted` boolean to `True
- hard `delete()` that removes the `Notification` instance from database

We would implement one of these method on a new Delete API endpoint exposed as  `DELETE /rest/inbox/<ID>`, removing the notification from the Vue.js list describe above on successfull deletions.

**Comment by pyoor** [comment]
I could see how it would be useful to have both.  Soft delete for "snoozing" notifications, and hard delete for removing them entirely. How difficult would it be to implement both? @jschwartzentruber, what are your thoughts?
