### ISSUE TITLE
Validate unaccessible bug notification wording

### ISSUE THREAD

**Issue by La0** [MozillaSecurity/FuzzManager#727]
Followup on @pyoor comment [here](https://github.com/MozillaSecurity/FuzzManager/pull/721#discussion_r667048997).

As there are several `Bucket` potentially tied to a single `Bug`, it seems complicated to generate a clean message mentionning all buckets.

**Comment by pyoor** [comment]
Closed via https://github.com/MozillaSecurity/FuzzManager/pull/766
