### ISSUE TITLE
Edit signature preview feature does not provide feedback

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/FuzzManager#734]
There is no indication of activity when previewing signature changes.

An error does eventually appear at the top of the screen.

`<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> `

**Comment by pyoor** [comment]
This really should be applied to all places where we're loading data (i.e. crashes, signatures, etc).  This could be as simple as adding https://bootstrap-vue.org/docs/components/spinner
