### ISSUE TITLE
Logging FM report in Bugzilla from template has issues

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/FuzzManager#749]
Resulting bug in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1720791

I tested logging an issue with template `Domino (assert)`.

It appears the template text was not populated properly. @choller mentioned that he could not edit the rendered text before posting.

FuzzManager displayed the following messages:
- Bug 1720791 was successfully submitted and created on bugzilla.mozilla.org provider. 
- An error occurred while attaching crash data to the created external bug: Failed to fetch attachment ID 9231452 from S3: The requested key was not found
- An error occurred while attaching the testcase to the created external bug: Network Error

**Comment by EvaBardou** [comment]
> It appears the template text was not populated properly.

FuzzManager now uses Mustache to render template variables, therefore you will need to update your templates following the new syntax (`%variable%` are to be replaced with `{{variable}}`).
See more details here: [Documentation: Bugzilla - Mustache.js variables](https://github.com/MozillaSecurity/FuzzManager/blob/master/doc/BugzillaVariables.md)

**Comment by choller** [comment]
> FuzzManager now uses Mustache to render template variables, therefore you will need to update your templates following the new syntax (`%variable%` are to be replaced with `{{variable}}`).

Thanks, I already suspected something like this :D 

There is still issues with attaching testcases (the one that got attached yesterday was garbled) and it would be nice to be able to edit the rendered version (I was doing that fairly often). Is that easy to accommodate in the new design?

**Comment by La0** [comment]
@choller Do you have  a link on Bugzilla with the garbled testcase (that should not happen), or maybe you can share the testcase itself ?

You already can edit a testcase if it's text-based (we do not display the binary ones).

If I understand correctly, you would like to edit the final version (in the rendered box), right before sending ?

That should be possible, but every modification would be lost if you modify the input box (as it would trigger a new render). We can discuss that on Tuesday's meeting as it seems like a new feature.

**Comment by pyoor** [comment]
Closing this as the initial issue has been resolved.
