### ISSUE TITLE
Upgrade to Django 3.2

### ISSUE THREAD

**Issue by La0** [MozillaSecurity/FuzzManager#857]
This is required to kickstart the GCP migration.

We need to upgrade the FuzzManager app to Django 3.2.

Steps:
1. check release notes for breaking changes from 2.2 to 3.2
2. identify potential issues
3. upgrade directly to 3.2
4. identify issues & django dependant plugins that may break

The first goal is to identify all issues and build a clear path for an upgrade. Then we'll be able to upgrade data & code.

**Comment by La0** [comment]
@jschwartzentruber BTW We can go all the way to 4.1 if you want (I guess 4.0 and 4.1 were not published when you wrote the initial issue)

**Comment by jschwartzentruber** [comment]
Fixed by #863 via #865
