### ISSUE TITLE
Coverage Report page should show the date

### ISSUE THREAD

**Issue by mozfreddyb** [MozillaSecurity/FuzzManager#939]
When going to an unpublished coverage Report Summary, e.g., covmanager/collections/xyz/summary/, it should show the date of said run.

If the stars align (and the django models have the right data somewhere nearby), I can try and give this a try, so I will assign it to myself.

**Comment by jschwartzentruber** [comment]
Fixed in https://github.com/MozillaSecurity/FuzzManager/commit/505b12a83afe1c624c4cf7167e5351c52aeefcb6
