### ISSUE TITLE
crashmanager/crashes/ shows nothing

### ISSUE THREAD

**Issue by JustSomeQuestions** [MozillaSecurity/FuzzManager#956]
Hi,
for some reason i can't figure out why the http://localhost:8000/crashmanager/crashes/ doesn't show any information. I've setup everything like in the tutorial and already pushed data to the server, but it doesn't show it in the browser.
Is the error on my side or is this a bug?

![image](https://github.com/MozillaSecurity/FuzzManager/assets/157353743/6ba0aa8d-6c98-48a3-a96a-7dcd2eb9df35)

Here are my config files: (I am using a WSL on windows for the setup and execution)
.htaccess:
![image](https://github.com/MozillaSecurity/FuzzManager/assets/157353743/d5abbba3-5182-4033-9d21-95040707f63f)
.fuzzmanagerconf:
![image](https://github.com/MozillaSecurity/FuzzManager/assets/157353743/2114403b-64ce-48b1-8c23-d34883267086)
.htpasswd:
![image](https://github.com/MozillaSecurity/FuzzManager/assets/157353743/1d1001f7-e1a8-4363-9dba-8590c22beb25)

![image](https://github.com/MozillaSecurity/FuzzManager/assets/157353743/5e8e012c-d9b3-4376-b874-3284b8798b66)

**Comment by jschwartzentruber** [comment]
> I've setup everything like in the tutorial

Which tutorial are you following? Is this in the fuzzing book or README.md?

I'm guessing you have errors in the console. I think the missing step is to run `cd server/frontend; npm i; npm run build`

**Comment by JustSomeQuestions** [comment]
I mainly flowed the README.md but used the fuzzing book as a more detailed version.
Tried the command line from above. Still a white screen.

**Comment by jschwartzentruber** [comment]
Did the `npm run build` command succeed? I reproduced the white screen problem, ran `npm run build` and then reran `runserver` and it worked.

main.js and main.css are the outputs from `npm run build`, so if they are 404 then the build didn't succeed.
